# Generated by Django 3.2.9 on 2021-12-04 21:29

from django.db import migrations
import rest_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', rest_auth.models.NewUserManager()),
            ],
        ),
    ]
