# Generated by Django 3.2.9 on 2021-12-04 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_auth', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
