# Generated by Django 3.2.9 on 2021-11-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexes', '0002_rename_index_etf'),
    ]

    operations = [
        migrations.AddField(
            model_name='etf',
            name='momentum_3',
            field=models.FloatField(null=True),
        ),
    ]
