# Generated by Django 3.2.9 on 2021-11-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('momentum_12_2', models.FloatField()),
                ('momentum_avg', models.FloatField()),
                ('ma10', models.IntegerField()),
                ('e_p', models.FloatField()),
                ('div_p', models.FloatField()),
            ],
        ),
    ]
