# Generated by Django 3.2.9 on 2021-11-08 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='index',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='stocks.index'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='index',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
