# Generated by Django 3.2.9 on 2021-11-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_stock_ma10'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='index',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ma10',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Index',
        ),
    ]
