# Generated by Django 3.2.9 on 2021-11-13 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_auto_20211108_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='stock',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.index'),
        ),
    ]
