# Generated by Django 3.2.9 on 2021-11-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_auto_20211113_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='name',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
